# Generated by Django 4.0.3 on 2022-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
